### ISSUE TITLE
Question: library maintenance

### ISSUE THREAD

**Issue by louboost** [scionoftech/webptools#1]
@scionoftech 
Hello,
Personally I like this your library. When I convert various images to webp files in using python language, it's very helpful to me.
But the library installed through WEBP official site on my local computer have a higher version than the webptools's cwebp. So there are differences in some converting results.
I just want to ask about the maintenance status of this library because it's been a while since you released initial version. Could you tell me, if there is any plan to update the version of libwebp?

**Comment by scionoftech** [comment]
Hi,
I have updated Webp Executables to version 1.0.3, please update webptools to version 0.0.2(https://pypi.org/project/webptools/)

Thank you
